# Proxmox VM Configuration
# This file defines all settings for VM deployment

# === VM SETTINGS ===
VM_NAME_PREFIX: "ubuntu"          # VM name will be: PREFIX-RELEASE-VMID
IMAGE_URL: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"

# Hardware
VM_MEMORY: "2048"                 # RAM in MB
VM_CORES: "2"                     # CPU cores
DISK_SIZE: "100G"                  # OS disk size (use +32G for relative)
VM_OS_TYPE: "l26"                 # Guest OS type (l26=Linux 2.6+, ubuntu, win11)

# Guest features
VM_AGENT: "true"                  # Enable QEMU Guest Agent
VM_BALLOON: "true"                # Enable memory ballooning (requires agent)

# Firmware and display
VM_BIOS: "seabios"                # Firmware: "seabios" (BIOS) or "ovmf" (UEFI)
VM_EFI_STORAGE: "A2000"       # Storage for EFI disk (only for UEFI)
VM_MACHINE: "q35"                 # Machine type (q35 or i440fx)
VM_CPU: "host"                    # CPU type (host, kvm64, max)
VM_VGA: "serial0"                 # Display (serial0, std, qxl, virtio)

# Virtual devices
VM_NET_MODEL: "virtio"            # Network card (virtio, e1000, rtl8139)
VM_NET_FIREWALL: "true"           # Enable Proxmox firewall for VM
VM_SCSI_TYPE: "virtio-scsi-pci"  # SCSI controller type
VM_SCSI_IOTHREAD: "true"          # Enable IO thread for better performance
VM_SCSI_SSD: "true"               # Emulate SSD (enables TRIM)

# Behaviour
VM_ONBOOT: "true"                 # Start VM when Proxmox boots
VM_AUTOSTART: "true"              # Start VM after creation
VM_PROTECTED: "false"             # Protect VM from accidental deletion
FORCE_DOWNLOAD: "false"           # Always re-download cloud image

# Metadata
VM_TAGS: "ubuntu,cloud-init"      # Comma-separated tags for organization

# === STORAGE & PATHS ===  
STORAGE_POOL: "A2000"         # Proxmox storage for VM disk
PROXMOX_ISO_DIR: "/var/lib/vz/template/iso"  # Where to store cloud images

# === NETWORK CONFIGURATION ===
NETWORK_BRIDGE: "vmbr0"           # Proxmox network bridge
NETWORK_TYPE: "static"              # Network type: "dhcp" or "static"

# Static IP settings (only used if NETWORK_TYPE is "static")
NETWORK_IP: "192.168.1.210/24"   # IP address with subnet mask
NETWORK_GATEWAY: "192.168.1.254"    # Gateway IP
NETWORK_DNS: "192.168.1.254"      # DNS servers (comma-separated)
NETWORK_DOMAIN: ""                # Search domain (optional)

# === PROVISIONING METHOD ===
VM_PROVISIONING: "cloud-init"     # Options: "cloud-init" or "none"

# Cloud-init settings (only used if VM_PROVISIONING is "cloud-init")
CI_USER: "antoine"                 # Username to create
CI_PASSWORD: ""                   # Password (empty = prompt at runtime)
CI_SSH_KEY: "~/.ssh/id_rsa.pub"  # Path to SSH public key
CI_CUSTOM_CONFIG: ""              # Custom cloud-init config (advanced)