#ENC[AES256_GCM,data:xMYVo50G8CLeM+gxhRTYdtzs9rF/M0qGUGymGmftcnbCmYIpYzl0d1OFcKm1Qxt+U/49BzhhpggU9no3+RaYbLpgV8ZxeA==,iv:nepLJv8SossoSSkPwTX4M5cyf7X4TYJUuYNXmtOfYaI=,tag:KNd3QWYRqW5QxyqcCV9VVw==,type:comment]
#ENC[AES256_GCM,data:OfL6d/ENSo+iGzZZLgpHAW/4cJqwuyt5fqZEC6e/pSO4klEn3I9A38bh1rxlRBY=,iv:3zhbtFUBQKcoAb1y9ddfT2Xq5gXcioAJZ2/wv7qbMME=,tag:gP6UWr/2j18OjvHnXvD3Hw==,type:comment]
proxmox_api_url: ENC[AES256_GCM,data:7nWTQvAmAtNUlbsd9Im5u1o/atHIQ49pVP4YdpZcOImRb4f0,iv:hiO+f3J2Op6KRukQ6LFzU2YYU8/t5C3ajiLD/M96BAc=,tag:2r0kZ1OBTndL8XwnHmUNdA==,type:str]
proxmox_node: ENC[AES256_GCM,data:FPBbPO5G+A==,iv:+KZiYyNr4qbr/dJf5m2jWVTmbMpQUqdM5sb1jKxD0Ko=,tag:s4jk+HK+3J0Q1BFHkH5+yg==,type:str]
proxmox_api_token_id: ENC[AES256_GCM,data:CwcM0yLhdL/UTVedWZZLWoECrRzAP8Ydz+VFpoa6Tg==,iv:2ogSVae1PltgdpLVs9bJReHsugbGNeSRBqrZDq/0JDU=,tag:qdCkbz74pNZjlqwPcDgcJA==,type:str]
proxmox_api_token_secret: ENC[AES256_GCM,data:eFbeSHVILrPmjbxkqUuUv8/p64CzY15rAsepVDNbXe//9m0G,iv:V4hKDDWqVJ2i0Ej1nCWr9p6R8nsPWk+sfmQirHKCftw=,tag:bmkdjSElAOdyC5wTv109iw==,type:str]
ssh_public_key: ""
cloud_init_password: ENC[AES256_GCM,data:mKxT11HRAQ==,iv:m6MT59T1Dd0vkc5pPcESaRWVpteUBx5+Hrt9F+fRgMo=,tag:eMF1d5j7sIW8EL2u2nV6Ow==,type:str]
cloud_init_user: ENC[AES256_GCM,data:OZ4QQIjhLw==,iv:X0EciLL63WYl2MvN0000qTwF9DWHZxkWMdXckpfetek=,tag:YQG0GlKTbszirDAcC5JJYw==,type:str]
sops:
    age:
        - recipient: age1hmqdqshufu0rdpcn2vj0r2f38zsn5lqnfv879ws24c2mnc4urfjqw36d5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YVRhbm1OSGl0MFluZHVL
            N25ENDFLeDRqYmdSSGVXMzNLRW84WXlSazNnCll4VG9MbTFZUWVHekVxNnNyRmtF
            dTJJOFduV0FDMlEwNnZxcGxJOTBOQzgKLS0tIGx2ZE9pbXpKU3MxRkQxUVlYekhV
            Z2c5OS9VekNOSFlWRUlhVlZ5VnVMODQKr6M9ivNhMsO1Ert6wL6p4btg1Up12/Cd
            kzNi4JLWy7pvSELyRqeXPKLtqKvnf5wrQqTsMgbowL2fpTGUKOSoGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T19:40:46Z"
    mac: ENC[AES256_GCM,data:CvhAS941WvQxlD7SwkOXm28iBN/b5S9jehA28VcKmAhob0gUbbnRj3D2OMNDNSgNsQNVnSUbbZHSKtVWrQF9q/FlPCT141+maXay9a6ZUzTlLuk1tep6ai4XZIOpWfe1eskYD+cwCbYgSecNeuCZWtvOKEl0ueN2az+SlBkJ2+o=,iv:fJsVqNa5Y12wJCnkEmy8i98naGdN5qwz2i1R18bgxBc=,tag:tfYf5QWvyLNy3EM53TLvnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
