#ENC[AES256_GCM,data:ZlOQU8p2p8MMPDHk2+MAmv+IFMB/CcPhTwLTaQLHtpvYlM1hyZpS4hkx7zTRkPjJbM8UtvHFhUS0nyUdQd6eMS3tte4WiA==,iv:ZYZIykNpUch03MK7TfvKMBVwjs10/jbYiUzelITlk3o=,tag:h/wu/YbJvI0eMLuZsS5CNQ==,type:comment]
#ENC[AES256_GCM,data:/wiDByKswVFIpDAsWiZ0WYRO3F7+IkdGBANLFoy7W9uuWlcWWAlWDR1ui64U59I=,iv:vWEcQAPNA04kOooMBueSc7+APRhIzHP7Ck0vA+va5hY=,tag:E+2as0AGYxcbv4P0XfayXw==,type:comment]
proxmox_api_url: ENC[AES256_GCM,data:zyr8BOXm28y+RfPgTiYkLjbc2XsP4qftSt4niwSkRJxEgddb,iv:XAG1aqb3x/ODx2kWZq+TtTJ79G/JsY4d5W10nPK7KME=,tag:lYVLjdL7M+7cYMwcqSReww==,type:str]
proxmox_node: ENC[AES256_GCM,data:4dR+SYh0pg==,iv:Tn28hi74QH6pX3Uhv+HVP7uMlvtbPbba7Qwq2zntklY=,tag:hm4oVjS5e6VMGZT2URqSHg==,type:str]
proxmox_api_token_id: ENC[AES256_GCM,data:68FTpXSvx6ioECgGCxPrCeVf2tjf05kpafUBXRxLNg==,iv:MWa+bK0yT8UNhLoR7VDbNVSibzS3KYbVh7YTNx0bQ+w=,tag:a2TARs4DVX4TR0KIupipsQ==,type:str]
proxmox_api_token_secret: ENC[AES256_GCM,data:wslhQwfekrNMRtmON7UfAKuJbllOgdn6g9hNJZ0EQ0PQFEHP,iv:aSFc4v8qzoAwkd18L5DwnDuWnXwEE+TWVpCBSM2OdKU=,tag:mafUOvimev+VF33YKyHcJg==,type:str]
ssh_public_key: ""
cloud_init_password: ENC[AES256_GCM,data:MqjhkGBWrQ==,iv:k8rFLstHOkAJUOX53UmzPaVIqib2WBLhSeA0Lk1W8ow=,tag:rLWLhh0dg3ybUNuXe5fIXQ==,type:str]
cloud_init_user: ENC[AES256_GCM,data:1Spqm5CvaA==,iv:jEmzlNLFx3x8h+zEeK1PX9RMlSzEzavgxFJXZvmBr2s=,tag:qPpCXbL8zg4J3cio8ggHlA==,type:str]
sops:
    age:
        - recipient: age1hmqdqshufu0rdpcn2vj0r2f38zsn5lqnfv879ws24c2mnc4urfjqw36d5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OERHdU9RbUhmdE5tVWE3
            Vms1NFJPUk03RFd1RzZNcWMxa2pkS0YrQ0N3CkZCc1J2UnNDeHN1T3ZjeUlFenlQ
            ZDQ0ZlhwU2JWS05iU2VHL3pRbStudHMKLS0tIDJmM2lJZEN0dWl4TjdaKzd2blBY
            YmJrNUZHV2RON0tvQng4SWNib2ZBNkEKrE1rjYreVwRDyfQsrM8iPGy4RDqcwv0h
            +x/oRUeCmPkFjGrEiCL8yZR55sVBWl3x97l3XGLVgM4rIe90ezbdhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T21:02:55Z"
    mac: ENC[AES256_GCM,data:/MWj5Zj1EsfVhzn5z7jrXZuSG1MmmF+n+1drqa6hCcBFkDZn8y5DXtjeLNq9DATZTTdjIz+SaBlOS7tBqSMbY0NbusqqA0kW6geEsFUUoPfjujPrElq8YNgK9V21k7Nd7qHdw7HJWPTA36veJTRNnXF0YziC/X6Q/oLkUj09CqQ=,iv:8SIKd7ikf7PEKQ8/YV+Yj/91oLYiaOi9sZedH6pIhd4=,tag:69LGlYzNcruwc/4hTFsNNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
